// src/plugins/rete/components/Node.vue
<template>
  <div 
    :class="[
      'relative flex flex-col rounded-[10px] min-w-[120px]',
      'bg-[rgba(110,136,255,0.8)] border-2 border-[#4e58bf]',
      selected ? 'bg-[#ffd92c] border-[#e3c000]' : ''
    ]"
    :style="{ 
      width: (data.width || NODE_WIDTH) + 'px', 
      height: data.height ? data.height + 'px' : 'auto' 
    }"
    data-testid="node"
  >
    <div class="title text-white text-[18px] p-2 font-sans">
      {{ data.label }}
    </div>
    
    <!-- Outputs -->
    <div v-for="(output, key) in outputs" :key="key" class="output text-right">
      <span v-if="output" class="text-white text-[14px] align-middle mx-[6px]">{{ output.label }}</span>
      <span class="inline-block w-[12px] h-[12px] rounded-full bg-[#96b38a] border border-white align-middle" />
    </div>
    
    <!-- Controls -->
    <div v-for="(control, key) in controls" :key="key">
      <template v-if="control">
        <!-- Control rendering handled by separate component -->
      </template>
    </div>
    
    <!-- Inputs -->
    <div v-for="(input, key) in inputs" :key="key" class="input text-left">
      <span class="inline-block w-[12px] h-[12px] rounded-full bg-[#96b38a] border border-white align-middle" />
      <span v-if="input && (!input.control || !input.showControl)" class="text-white text-[14px] align-middle mx-[6px]">{{ input.label }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { SOCKET_SIZE, SOCKET_MARGIN, NODE_WIDTH } from '../presets/classic'

interface NodeData {
  id: string
  label: string
  width?: number
  height?: number
  selected?: boolean
  inputs?: Record<string, { label?: string; control?: unknown; showControl?: boolean; socket?: unknown }>
  outputs?: Record<string, { label?: string; control?: unknown; showControl?: boolean; socket?: unknown }>
  controls?: Record<string, unknown>
}

const props = defineProps<{
  data: NodeData
}>()

const inputs = computed(() => props.data.inputs || {})
const outputs = computed(() => props.data.outputs || {})
const controls = computed(() => props.data.controls || {})
const selected = computed(() => props.data.selected || false)
</script>

// rete-react-plugin/presets/classic/components/Node.tsx
import * as React from 'react'

import { ClassicScheme, RenderEmit } from '../types'
import { RefControl } from './refs/RefControl'
import { RefSocket } from './refs/RefSocket'

type NodeExtraData = { width?: number, height?: number }

function sortByIndex<T extends [string, undefined | { index?: number }][]>(entries: T) {
  entries.sort((a, b) => {
    const ai = a[1]?.index || 0
    const bi = b[1]?.index || 0

    return ai - bi
  })
}

type Props<S extends ClassicScheme> = {
  data: S['Node'] & NodeExtraData
  styles?: () => any
  emit: RenderEmit<S>
}
export type NodeComponent<Scheme extends ClassicScheme> = (props: Props<Scheme>) => JSX.Element

export function Node<Scheme extends ClassicScheme>(props: Props<Scheme>) {
  const inputs = Object.entries(props.data.inputs)
  const outputs = Object.entries(props.data.outputs)
  const controls = Object.entries(props.data.controls)
  const selected = props.data.selected || false
  const { id, label, width, height } = props.data

  sortByIndex(inputs)
  sortByIndex(outputs)
  sortByIndex(controls)

  const nodeClasses = [
    'relative',
    'cursor-pointer',
    'select-none',
    'font-arial',
    'leading-normal',
    'pb-1.5',
    'box-border',
    selected
      ? 'bg-[#ffd92c] border-[#e3c000]'
      : 'bg-[rgba(110,136,255,0.8)] border-[#4e58bf]',
    'rounded-[10px]',
    'border-2',
    'user-select-none',
  ].join(' ')

  return (
    <div
      className={nodeClasses}
      style={{ width: width || 180, height: height || 'auto' }}
      data-testid="node"
    >
      <div className="text-white font-sans text-lg p-2" data-testid="title">{label}</div>
      {/* Outputs */}
      {outputs.map(([key, output]) => output && <div className="text-right" key={key} data-testid={`output-${key}`}>
        <div className="text-white font-sans text-sm m-2 inline-block align-middle leading-3">{output.label}</div>
        <div className="text-right -mr-3 inline-block">
          <RefSocket
            name="output-socket"
            side="output"
            socketKey={key}
            nodeId={id}
            emit={props.emit}
            payload={output.socket}
            data-testid="output-socket"
          />
        </div>
      </div>)}
      {/* Controls */}
      {controls.map(([key, control]) => {
        return control
          ? <RefControl
            key={key}
            name="control"
            emit={props.emit}
            payload={control}
            data-testid={`control-${key}`}
          />
          : null
      })}
      {/* Inputs */}
      {inputs.map(([key, input]) => input && <div className="text-left" key={key} data-testid={`input-${key}`}>
        <div className="-ml-3 inline-block">
          <RefSocket
            name="input-socket"
            side="input"
            socketKey={key}
            nodeId={id}
            emit={props.emit}
            payload={input.socket}
            data-testid="input-socket"
          />
        </div>
        {input && (!input.control || !input.showControl)
        && <div className="text-white font-sans text-sm m-2 inline-block align-middle leading-3" data-testid="input-title">{input.label}</div>
        }
        {input.control && input.showControl && (
          <RefControl
            key={key}
            name="input-control"
            emit={props.emit}
            payload={input.control}
            data-testid="input-control"
          />
        )
        }
      </div>)}
    </div>
  )
}
