// demo/src/Playground.tsx
'use client'
import { Editor } from '@monaco-editor/react';
import { editor as monaco } from 'monaco-editor';
import React, { useEffect, useState } from 'react';
import { LanguageAdapter } from 'rete-studio-core';
import styled from 'styled-components';
import { useDebounceValue } from 'usehooks-ts'

import { CodeError } from './shared/Alert';
import { Area } from './shared/Area';
import { CopyCode } from './shared/CopyCode';
import { useEditor } from './shared/Editor';
import { Spin } from './shared/Spin'
import { Theme } from './theme';

const Layout = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: 2fr 3fr;
  grid-template-areas:
    'source result'
    'canvas canvas';
  gap: 0.6em;
  padding: 0.6em;
  box-sizing: border-box;
  overflow: hidden;
  @media (max-height: 500px) {
    grid-template-columns: minmax(300px, 1fr) 3fr;
    grid-template-rows: 1fr 1fr;
    grid-template-areas:
      'source canvas'
      'result canvas';
  }
  @media (max-width: 400px) {
    grid-template-columns: 1fr;
    grid-template-rows: 1fr 2fr 1fr;
    grid-template-areas:
      'source'
      'canvas'
      'result';
  }
`

const Source = styled(Area)`
  grid-area: source;
  position: relative;
`

const Result = styled(Area)`
  grid-area: result;
  position: relative;
`

const Canvas = styled(Area)`
  grid-area: canvas;
  position: relative;
`

export function Playground({ lang, example, switchLang }: { switchLang: React.ReactNode, example: string, lang: LanguageAdapter }) {
  const [code, setCode] = useState<string | undefined>()
  const [debouncedCode] = useDebounceValue(code, 500)
  const editor = useEditor({ lang, code: debouncedCode })

  useEffect(() => {
    setCode(example)
  }, [example])

  const options: monaco.IStandaloneEditorConstructionOptions = {
    minimap: {
      enabled: false,
    },
    padding: { top: 10 }
  }

  return (
    <Theme>
      <Layout>
        <Source>
          <Editor
            theme="vs-dark"
            language="javascript"
            value={code}
            onChange={setCode}
            options={options}
          />
          {switchLang}
          {editor.codeToGraph.status && <CodeError message={editor.codeToGraph.status?.message} placement="right" />}
        </Source>
        <Result>
          <Spin spinning={editor.graphToCode.loading} />
          <Editor
            theme="vs-dark"
            language="javascript"
            value={editor.code}
            options={{ readOnly: true, ...options }}
          />
          <CopyCode value={editor.executableCode || ''} />
          {editor.graphToCode.status && <CodeError message={editor.graphToCode.status?.message} placement="right" />}
        </Result>
        <Canvas>
          <Spin spinning={editor.codeToGraph.loading} size="large" />
          {editor.canvas}
        </Canvas>
      </Layout>
    </Theme>
  )
}

// src/components/Playground.vue
<template>
  <div class="h-screen grid grid-cols-2 gap-2 p-2 box-border overflow-hidden bg-gray-800">
    <!-- Source Code Panel -->
    <Area class-name="relative">
      <CodeEditor 
        v-model="sourceCode" 
        :language="'javascript'"
      />
      <Alert v-model="codeToGraphError" />
    </Area>

    <!-- Result Code Panel -->
    <Area class-name="relative">
      <Spin :spinning="graphToCodeLoading" />
      <CodeEditor 
        :model-value="resultCode" 
        :readonly="true"
        :language="'javascript'"
      />
      <CopyCode :value="executableCode || ''" />
      <Alert v-model="graphToCodeError" />
    </Area>

    <!-- Graph Canvas Panel -->
    <Area class-name="col-span-2 relative">
      <Spin :spinning="codeToGraphLoading" />
      <GraphCanvas ref="graphRef" :lang="lang" />
    </Area>
  </div>
  </template>

<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import type { LanguageAdapter } from 'rete-studio-core'
import Area from './shared/Area.vue'
import Spin from './shared/Spin.vue'
import Alert from './shared/Alert.vue'
import CopyCode from './shared/CopyCode.vue'
import CodeEditor from './CodeEditor.vue'
import GraphCanvas from './GraphCanvas.vue'

const props = defineProps<{
  lang: LanguageAdapter
  example: string
}>()

const sourceCode = ref(props.example)
const resultCode = ref('')
const executableCode = ref('')
const graphRef = ref<InstanceType<typeof GraphCanvas> | null>(null)

// Error states
const codeToGraphError = ref('')
const graphToCodeError = ref('')
const codeToGraphLoading = ref(false)
const graphToCodeLoading = ref(false)

onMounted(async () => {
  // Load example code
  sourceCode.value = props.example
  resultCode.value = props.example
  
  // Try to get example from language adapter
  if (props.lang) {
    try {
      const example = await props.lang.getExample()
      if (example) {
        sourceCode.value = example
        resultCode.value = example
      }
    } catch (e) {
      console.error('Failed to get example:', e)
    }
  }
})

watch(() => props.example, (val) => {
  sourceCode.value = val
  resultCode.value = val
})

// Watch source code changes and trigger code to graph
watch(sourceCode, async (newCode) => {
  if (!newCode || !props.lang) return
  
  codeToGraphLoading.value = true
  codeToGraphError.value = ''
  
  try {
    // Use the graph ref to convert code to graph
    if (graphRef.value) {
      await graphRef.value.codeToGraph(newCode)
    }
    
    // Then convert graph back to code
    graphToCodeLoading.value = true
    if (graphRef.value) {
      resultCode.value = await graphRef.value.graphToCode()
    }
    
    // Get executable code
    executableCode.value = await props.lang.codeToExecutable(resultCode.value)
  } catch (e) {
    codeToGraphError.value = (e as Error).message
  } finally {
    codeToGraphLoading.value = false
    graphToCodeLoading.value = false
  }
}, { debounce: 500 } as any)
</script>
