// demo-vue/src/App.vue
<template>
  <div id="app">
    <Playground
      v-if="lang"
      :lang="lang"
      :example="playgroundExample"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import Playground from './Playground.vue'
import type { LanguageAdapter } from 'rete-studio-core'

// Import workers
import JSWorker from './workers/javascript?worker'
import TemplateWorker from './workers/template?worker'
import { requestable, OnlyMethods } from 'worker-bridge'

const languages: Record<string, OnlyMethods<LanguageAdapter>> = {
  javascript: requestable<LanguageAdapter>(new JSWorker()),
  template: requestable<LanguageAdapter>(new TemplateWorker())
}

const currentLangKey = ref('javascript')
const lang = computed(() => languages[currentLangKey.value])
const playgroundExample = ref('')

onMounted(async () => {
  const example = await lang.value.getExample()
  playgroundExample.value = example
})
</script>

<style>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

html, body, #app {
  width: 100%;
  height: 100%;
  overflow: hidden;
}

body {
  font-family: 'Montserrat', sans-serif;
  background: rgb(62, 62, 62);
}
</style>

// demo/src/App.tsx
import { ConfigProvider } from 'antd'
import { Playground } from './Playground'
import { tokens } from './theme'
import { SwitchLang, useLang } from './Lang'
import { useEffect, useMemo, useState } from 'react'
import JSWorker from './workers/javascript?worker'
import TemplateWorker from './workers/template?worker'
import { OnlyMethods, requestable } from 'worker-bridge'
import { LanguageAdapter } from 'rete-studio-core'

const languages: Record<string, OnlyMethods<LanguageAdapter>> = {
  javascript: requestable<LanguageAdapter>(new JSWorker()),
  template: requestable<LanguageAdapter>(new TemplateWorker())
}

function App() {
  const langId = useLang()
  const lang = useMemo(() => languages[langId], [langId])
  const [playgroundExample, setPlaygroundExample] = useState<string>('')

  useEffect(() => {
    lang.getExample().then(setPlaygroundExample)
  }, [lang])

  return (
    <ConfigProvider
      theme={{
        token: tokens
      }}
    >
      <Playground
        example={playgroundExample}
        lang={lang}
        switchLang={<SwitchLang />}
      />
    </ConfigProvider>
  )
}

export default App
