// demo-vue/src/Playground.vue
<template>
  <div class="playground">
    <!-- Toolbar -->
    <div class="toolbar">
      <button class="toolbar-btn" @click="handleGraphToCode" :disabled="graphToCodeLoading" title="To code">
        <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor"><path d="M9.4 16.6L4.8 12l4.6-4.6L8 6l-6 6 6 6 1.4-1.4zm5.2 0l4.6-4.6-4.6-4.6L16 6l6 6-6 6-1.4-1.4z"/></svg>
      </button>
      <button class="toolbar-btn" @click="handleLayout" title="Layout">
        <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor"><path d="M3 5v14h18V5H3zm16 12H5V7h14v10z"/></svg>
      </button>
    </div>

    <!-- Main Grid Layout -->
    <div class="layout-grid">
      <!-- Source Code Editor -->
      <div class="source-panel">
        <div ref="sourceEditorRef" class="editor-container" />
        <LangSwitch class="lang-switch" />
        <div v-if="codeToGraphError" class="error-alert">
          {{ codeToGraphError }}
        </div>
      </div>

      <!-- Result Code Editor -->
      <div class="result-panel">
        <div ref="resultEditorRef" class="editor-container" />
        <div v-if="graphToCodeLoading" class="loading-spin">
          <div class="spinner"></div>
        </div>
        <button class="copy-button" @click="handleCopyCode" title="Copy executable code">
          <svg viewBox="0 0 24 24" width="16" height="16" fill="currentColor"><path d="M16 1H4c-1.1 0-2 .9-2 2v14h2V3h12V1zm3 4H8c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h11c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2zm0 16H8V7h11v14z"/></svg>
        </button>
        <div v-if="graphToCodeError" class="error-alert">
          {{ graphToCodeError }}
        </div>
      </div>

      <!-- Canvas Editor -->
      <div class="canvas-panel">
        <div ref="canvasRef" class="canvas-container" />
        <div v-if="codeToGraphLoading" class="loading-spin">
          <div class="spinner"></div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue'
import type { editor as MonacoEditor } from 'monaco-editor'
import { createEditor } from './editor'
import { tokens } from './theme'
import LangSwitch from './Lang.vue'
import type { LanguageAdapter, LanguageSnippet } from 'rete-studio-core'

// Import workers
import JSWorker from './workers/javascript?worker'
import TemplateWorker from './workers/template?worker'
import { requestable, OnlyMethods } from 'worker-bridge'

const languages: Record<string, OnlyMethods<LanguageAdapter>> = {
  javascript: requestable<LanguageAdapter>(new JSWorker()),
  template: requestable<LanguageAdapter>(new TemplateWorker())
}

type Props = {
  lang: LanguageAdapter
  example: string
  switchLang?: any
}

const props = defineProps<Props>()

// Refs
const sourceEditorRef = ref<HTMLElement | null>(null)
const resultEditorRef = ref<HTMLElement | null>(null)
const canvasRef = ref<HTMLElement | null>(null)

// State
const codeToGraphLoading = ref(false)
const graphToCodeLoading = ref(false)
const codeToGraphError = ref<string | null>(null)
const graphToCodeError = ref<string | null>(null)
const currentCode = ref<string | undefined>()
const executableCode = ref<string | undefined>()

// Editor instances
let sourceEditor: MonacoEditor.IStandaloneCodeEditor | null = null
let resultEditor: MonacoEditor.IStandaloneCodeEditor | null = null
let editor: ReturnType<typeof createEditor> | null = null

const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))

async function handleGraphToCode() {
  if (!editor) return
  graphToCodeLoading.value = true
  graphToCodeError.value = null
  try {
    await delay(400)
    const [, code] = await Promise.all([
      delay(400),
      editor.graphToCode()
    ])
    currentCode.value = code
    resultEditor?.setValue(code)
  } catch (e) {
    graphToCodeError.value = (e as Error).message
  } finally {
    graphToCodeLoading.value = false
  }
}

async function handleLayout() {
  if (!editor) return
  await editor.layout()
}

async function handleCopyCode() {
  if (executableCode.value) {
    await navigator.clipboard.writeText(executableCode.value)
    // Show copied feedback via CSS
    const btn = document.querySelector('.copy-button') as HTMLButtonElement
    if (btn) {
      btn.classList.add('copied')
      setTimeout(() => btn.classList.remove('copied'), 1000)
    }
  }
}

onMounted(async () => {
  // Get initial example
  const example = await props.lang.getExample()
  sourceEditor?.setValue(example)

  // Create source editor
  if (sourceEditorRef.value) {
    const monaco = await import('monaco-editor')
    sourceEditor = monaco.editor.create(sourceEditorRef.value, {
      value: example,
      language: 'javascript',
      theme: 'vs-dark',
      minimap: { enabled: false },
      padding: { top: 10 },
    })

    sourceEditor.onDidChangeModelContent(() => {
      const code = sourceEditor?.getValue()
      if (code && editor) {
        codeToGraphLoading.value = true
        codeToGraphError.value = null
        delay(500).then(async () => {
          try {
            await editor!.codeToGraph(code)
            executableCode.value = await editor!.codeToExecutable(code)
            await handleGraphToCode()
          } catch (e) {
            codeToGraphError.value = (e as Error).message
          } finally {
            codeToGraphLoading.value = false
          }
        })
      }
    })
  }

  // Create result editor
  if (resultEditorRef.value) {
    const monaco = await import('monaco-editor')
    resultEditor = monaco.editor.create(resultEditorRef.value, {
      value: '',
      language: 'javascript',
      theme: 'vs-dark',
      minimap: { enabled: false },
      padding: { top: 10 },
      readOnly: true,
    })
  }

  // Create canvas editor
  if (canvasRef.value) {
    const snippets = await props.lang.getSnippets()
    editor = await createEditor(canvasRef.value, snippets, props.lang)
  }
})

onUnmounted(() => {
  editor?.destroy()
  sourceEditor?.dispose()
  resultEditor?.dispose()
})

watch(() => props.example, async (newExample) => {
  if (newExample && sourceEditor) {
    sourceEditor.setValue(newExample)
  }
})
</script>

<style scoped>
.playground {
  width: 100vw;
  height: 100vh;
  display: flex;
  flex-direction: column;
  background: rgb(62, 62, 62);
}

.toolbar {
  position: absolute;
  top: 1em;
  right: 1em;
  z-index: 10;
  display: flex;
  gap: 0.5em;
}

.toolbar-btn {
  width: 36px;
  height: 36px;
  border: none;
  border-radius: 6px;
  background: rgba(255, 255, 255, 0.1);
  color: white;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: background 0.2s;
}

.toolbar-btn:hover {
  background: rgba(255, 255, 255, 0.2);
}

.toolbar-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.layout-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: 2fr 3fr;
  grid-template-areas:
    "source result"
    "canvas canvas";
  gap: 0.6em;
  padding: 0.6em;
  box-sizing: border-box;
  overflow: hidden;
  height: 100%;
}

.source-panel,
.result-panel,
.canvas-panel {
  position: relative;
  border-radius: 1em;
  overflow: hidden;
  border: 2px solid #464646;
  background: #1e1e1e;
  color: white;
}

.source-panel {
  grid-area: source;
}

.result-panel {
  grid-area: result;
}

.canvas-panel {
  grid-area: canvas;
}

.editor-container {
  width: 100%;
  height: 100%;
}

.canvas-container {
  width: 100%;
  height: 100%;
}

.lang-switch {
  position: absolute;
  bottom: 1em;
  right: 1em;
  z-index: 10;
}

.copy-button {
  position: absolute;
  bottom: 1em;
  right: 1em;
  z-index: 10;
  width: 32px;
  height: 32px;
  border: none;
  border-radius: 6px;
  background: rgba(255, 255, 255, 0.1);
  color: white;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: background 0.2s;
}

.copy-button:hover {
  background: rgba(255, 255, 255, 0.2);
}

.copy-button.copied {
  background: rgba(76, 175, 80, 0.3);
}

.loading-spin {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 5;
  background: rgba(0, 0, 0, 0.3);
}

.spinner {
  width: 40px;
  height: 40px;
  border: 3px solid rgba(255, 255, 255, 0.1);
  border-top-color: #fff;
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.error-alert {
  position: absolute;
  bottom: 1em;
  left: 1em;
  right: 4em;
  z-index: 14;
  background: rgba(244, 67, 54, 0.2);
  border: 1px solid rgba(244, 67, 54, 0.5);
  border-radius: 6px;
  padding: 0.5em 1em;
  color: #ff6b6b;
  font-size: 0.85em;
}

@media (max-height: 500px) {
  .layout-grid {
    grid-template-columns: minmax(300px, 1fr) 3fr;
    grid-template-rows: 1fr 1fr;
    grid-template-areas:
      "source canvas"
      "result canvas";
  }
}

@media (max-width: 400px) {
  .layout-grid {
    grid-template-columns: 1fr;
    grid-template-rows: 1fr 2fr 1fr;
    grid-template-areas:
      "source"
      "canvas"
      "result";
  }
}
</style>

// demo/src/Playground.tsx
'use client'
import { Editor } from '@monaco-editor/react';
import { editor as monaco } from 'monaco-editor';
import { useEffect, useState, useCallback } from 'react';
import { LanguageAdapter, LanguageSnippet } from 'rete-studio-core';
import styled from 'styled-components';
import { useDebounceValue } from 'usehooks-ts'
import { Spin as AntSpin } from 'antd'
import { DeliveredProcedureOutlined, CodeFilled, LayoutFilled } from '@ant-design/icons'
import { Button, Tooltip, message, Alert } from 'antd';
import { useRete } from 'rete-react-plugin';
import { createEditor } from './editor'
import { Theme } from './theme';

// Inline Alert component
const StyledAlert = styled(Alert)`
  position: absolute;
  bottom: 1em;
  z-index: 14;
`
function CodeError(props: { message: string, placement: 'left' | 'right' }) {
  return <StyledAlert
    type='error'
    message={props.message}
    showIcon={true}
    style={props.placement === 'left' ? { left: '1em' } : { right: '1em' }}
  />
}

// Inline Spin component
const Spin = styled(AntSpin)`
  position: absolute !important;
  top: 0 !important;
  left: 0 !important;
  width: 100% !important;
  height: 100% !important;
  z-index: 2;
  display: flex !important;
  align-items: center !important;
  justify-content: center !important;
  pointer-events: none !important;
`

// Inline Area component
const Area = styled.div`
  border-radius: 1em;
  overflow: hidden;
  border: 2px solid #464646;
  background: #1e1e1e;
  color: white;
`

// Inline CopyCode component
const CopyButton = styled(Button)`
  position: absolute !important;
  bottom: 1em;
  right: 1em;
  z-index: 20;
`
function CopyCode(props: { value: string }) {
  const [messageApi, contextHolder] = message.useMessage({ top: 20 });
  return (
    <Theme>
      {contextHolder}
      <Tooltip placement="top" title="Copy executable code">
        <CopyButton
          onClick={() => {
            navigator.clipboard.writeText(props.value)
            messageApi.info('Copied to clipboard')
          }}
          icon={<DeliveredProcedureOutlined />}
        />
      </Tooltip>
    </Theme>
  )
}

// Editor buttons
const SaveButton = styled(Button)`
  position: absolute !important;
  top: 1em;
  right: 1em;
  z-index: 1;
`
const LayoutButton = styled(Button)`
  position: absolute !important;
  bottom: 1em;
  right: 1em;
  z-index: 1;
`

const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

function useTask(props: { execute: () => unknown | Promise<unknown>, fail: () => unknown | Promise<unknown> }) {
  const [loading, setLoading] = useState(false)
  const [status, setStatus] = useState<{ type: 'success' | 'error', message: string } | null>(null)

  return {
    loading,
    status,
    async execute() {
      try {
        setLoading(true)
        setStatus(null)
        await props.execute()
      } catch (e) {
        await props.fail()
        setStatus({ type: 'error', message: (e as Error).message })
        console.error(e)
      } finally {
        setLoading(false)
      }
    }
  }
}

function useEditor(props: { lang: LanguageAdapter, code: string | undefined, autoCode?: boolean }) {
  const [snippets, setSnippets] = useState<LanguageSnippet[]>([])

  const create = useCallback((container: HTMLElement) => {
    return createEditor(container, snippets, props.lang)
  }, [snippets, props.lang])
  const [ref, editor] = useRete(create)
  const [code, setCode] = useState<string | undefined>()
  const [executableCode, setExecutableCode] = useState<undefined | string>()

  useEffect(() => {
    props.lang.getSnippets().then(setSnippets)
  }, [props.lang])

  useEffect(() => {
    if (code && editor) {
      editor.codeToExecutable(code).then(setExecutableCode)
    } else setExecutableCode(undefined)
  }, [code, editor])

  const codeToGraph = useTask({
    async execute() {
      if (!editor || !props.code) return
      await Promise.all([delay(400), editor.codeToGraph(props.code)])
    },
    fail: () => editor?.clear()
  })
  const graphToCode = useTask({
    async execute() {
      if (!editor) return
      const [, code] = await Promise.all([delay(400), editor.graphToCode()])
      setCode(code)
    },
    fail: () => setCode('// can\'t transpile graph into code')
  })

  useEffect(() => {
    if (props.code && editor) {
      void async function () {
        await codeToGraph.execute()
        if (props.autoCode !== false) await graphToCode.execute()
      }()
    }
  }, [editor, props.code])

  return {
    codeToGraph,
    graphToCode,
    code,
    executableCode,
    canvas: (
      <Theme>
        <Tooltip placement="bottom" title="To code">
          <SaveButton onClick={graphToCode.execute} icon={<CodeFilled />} />
        </Tooltip>
        <Tooltip placement="top" title="Layout">
          <LayoutButton onClick={() => editor?.layout()} icon={<LayoutFilled />} />
        </Tooltip>
        <div ref={ref} style={{ height: '100%', width: '100%' }} />
      </Theme>
    )
  }
}

const LayoutGrid = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: 2fr 3fr;
  grid-template-areas:
    'source result'
    'canvas canvas';
  gap: 0.6em;
  padding: 0.6em;
  box-sizing: border-box;
  overflow: hidden;
  @media (max-height: 500px) {
    grid-template-columns: minmax(300px, 1fr) 3fr;
    grid-template-rows: 1fr 1fr;
    grid-template-areas:
      'source canvas'
      'result canvas';
  }
  @media (max-width: 400px) {
    grid-template-columns: 1fr;
    grid-template-rows: 1fr 2fr 1fr;
    grid-template-areas:
      'source'
      'canvas'
      'result';
  }
`

const Source = styled(Area)`
  grid-area: source;
  position: relative;
`

const Result = styled(Area)`
  grid-area: result;
  position: relative;
`

const Canvas = styled(Area)`
  grid-area: canvas;
  position: relative;
`

export function Playground({ lang, example, switchLang }: { switchLang: React.ReactNode, example: string, lang: LanguageAdapter }) {
  const [code, setCode] = useState<string | undefined>()
  const [debouncedCode] = useDebounceValue(code, 500)
  const editor = useEditor({ lang, code: debouncedCode })

  useEffect(() => {
    setCode(example)
  }, [example])

  const options: monaco.IStandaloneEditorConstructionOptions = {
    minimap: { enabled: false },
    padding: { top: 10 }
  }

  return (
    <Theme>
      <LayoutGrid>
        <Source>
          <Editor theme="vs-dark" language="javascript" value={code} onChange={setCode} options={options} />
          {switchLang}
          {editor.codeToGraph.status && <CodeError message={editor.codeToGraph.status?.message} placement="right" />}
        </Source>
        <Result>
          <Spin spinning={editor.graphToCode.loading} />
          <Editor theme="vs-dark" language="javascript" value={editor.code} options={{ readOnly: true, ...options }} />
          <CopyCode value={editor.executableCode || ''} />
          {editor.graphToCode.status && <CodeError message={editor.graphToCode.status?.message} placement="right" />}
        </Result>
        <Canvas>
          <Spin spinning={editor.codeToGraph.loading} size="large" />
          {editor.canvas}
        </Canvas>
      </LayoutGrid>
    </Theme>
  )
}
